#!/usr/bin/env bash

set -e

echo "Job started: $(date)"

source /usr/local/bin/pg2swift-build-swift-env

DUMP_OUTPUT_PATH="/tmp/$(date +"%Y%m%d-%H%M%S").sql"

echo "Dumping $PGDATABASE from $POSTGRES_PORT_5432_TCP_ADDR:$POSTGRES_PORT_5432_TCP_PORT to $DUMP_OUTPUT_PATH"

# pg_dump will dump the database content
# -Z2 compression level set to 2 (higer you compress, longer the dump will take)
# -Fc use the custom format
# --host Linked PostgreSQL Docker container address
# --port Linked PostgreSQL Docker container port
# --username used to connect to PostgreSQL
#
# No database variable given as PostgreSQL uses PGDATABASE as default one.
pg_dump -Z2 -Fc --host=$POSTGRES_PORT_5432_TCP_ADDR \
  --port=$POSTGRES_PORT_5432_TCP_PORT \
  --username=postgres > $DUMP_OUTPUT_PATH

DUMP_SIZE=`ls -alh $DUMP_OUTPUT_PATH | awk '{ print $5 }'`
echo "Uploading $DUMP_OUTPUT_PATH ($DUMP_SIZE) to the OpenStack Swift container $OS_CONTAINER_NAME ..."
$SWIFT_CMD upload $OS_CONTAINER_NAME "$DUMP_OUTPUT_PATH"

rm "$DUMP_OUTPUT_PATH"

echo "Job finished: $(date)"
